### ISSUE TITLE
consider referencing firefox's plans to strip query parameters

### ISSUE THREAD

**Issue by wanderview** [privacycg/nav-tracking-mitigations#20]
Currently this only discusses firefox's redirect tracking protection:

https://privacycg.github.io/nav-tracking-mitigations/#mitigations-firefox

Should it also mention that firefox is working on query parameter stripping?  See:

https://groups.google.com/a/mozilla.org/g/dev-platform/c/1vOSas0ptVQ

**Comment by wanderview** [comment]
Its also mentioned as being "enabled" in this post:

https://groups.google.com/a/mozilla.org/g/dev-platform/c/p6Mad1gtw7g/m/r0cS93MNBgAJ

**Comment by Trikolon** [comment]
It's currently only enabled in Nightly. However we're planning to enable it with an initial list in Fx102 in strict ETP mode and in private browsing.
