### ISSUE TITLE
Delete CHIPS cookies

### ISSUE THREAD

**Issue by bvandersloot-mozilla** [privacycg/nav-tracking-mitigations#75]
When (deleting cookies)[https://privacycg.github.io/nav-tracking-mitigations/#clear-cookies-for-host], only cookies whose domain key matches are deleted. We should also delete cookies whose partition key is same-site-host with the host to be deleted.

**Comment by wanderview** [comment]
Just to clarify, the "partition key" is the top-level site in the partitioned case, right?  So in "A->B" it refers to the A here?  If so, think we implement this but the spec was not updated.

**Comment by bvandersloot-mozilla** [comment]
That's correct! I expected that was the case.
