### ISSUE TITLE
Would you review this? (Total Tracking Protection)

### ISSUE THREAD

**Issue by MasterInQuestion** [privacycg/nav-tracking-mitigations#77]
Total Tracking Protection
    [ https://github.com/MasterInQuestion/talk/discussions/12](https://github.com/MasterInQuestion/talk/discussions/12)

    Partly posted for some time, but didn't gain attention from Mozilla.

    Regardless I'm constantly refining it.
    And have further plan even if Mozilla did decide to ignore it.

    Related:
    Losing Battle against Global Advisary
    [ https://github.com/MasterInQuestion/talk/discussions/29](https://github.com/MasterInQuestion/talk/discussions/29)

**Comment by jyasskin** [comment]
It's not appropriate to post issues that aren't clearly related to navigational tracking in this repository, or to ask the reviewers here to click through to another issue to figure that out. Closing this as off-topic.
